--region [dbo].[spciDivisionDelete]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spciDivisionDelete]
-- Date Generated: Friday, June 29, 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spciDivisionDelete]
	@DivisionKey int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[tciDivision]
WHERE
	[tciDivision].[DivisionKey] = @DivisionKey

--endregion

GO