--region [dbo].[spciDivisionUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spciDivisionUpdate]
-- Date Generated: Friday, June 29, 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spciDivisionUpdate]
		@DivisionKey int,
		@DivisionId nvarchar(50),
		@DivisionValue int,
		@ModifiedByUserKey int,
		@Name nvarchar(200),
		@LastChanged timestamp,
		@NewLastChanged timestamp OUTPUT
AS

SET NOCOUNT ON

UPDATE [dbo].[tciDivision] SET
		[DivisionId] = @DivisionId,
		[DivisionValue] = @DivisionValue,
		[ModifiedByUserKey] = @ModifiedByUserKey,
		ModifiedOnDate = getdate(),
		[Name] = @Name
WHERE
	[tciDivision].[DivisionKey] = @DivisionKey
AND	
	[tciDivision].[LastChanged] = @LastChanged

IF	@@ROWCOUNT = 0	
	BEGIN
		RAISERROR('Row has been edited by another user.  Your changes will be lost.',16,1)
	END
	
SELECT 
	@NewLastChanged = LastChanged
FROM 
	[dbo].[tciDivision]
WHERE 	
	[tciDivision].[DivisionKey] = @DivisionKey

--endregion

GO	