--region [dbo].[spciDivisionInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spciDivisionInsert]
-- Date Generated: Friday, June 29, 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spciDivisionInsert]
		@CreatedByUserKey int,
		@DivisionId nvarchar(50),
		@DivisionValue int,
		@Name nvarchar(200),
		@NewDivisionKey int output,
		@NewLastChanged timestamp output
AS

SET NOCOUNT ON

INSERT INTO [dbo].[tciDivision] (
	[CreatedByUserKey],
	[CreatedOnDate],
	[DivisionId],
	[DivisionValue],
	[Name]
) VALUES (
	@CreatedByUserKey,
	getdate(),
	@DivisionId,
	@DivisionValue,
	@Name
)

SET @NewDivisionKey = SCOPE_IDENTITY()

SELECT @NewLastChanged = LastChanged
FROM [dbo].[tciDivision]
WHERE DivisionKey = @NewDivisionKey

--endregion

GO