--region [dbo].[spciDivisionListSelect]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spciDivisionListSelect]
-- Date Generated: Friday, June 29, 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spciDivisionListSelect]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT
	[tciDivision].[DivisionKey],
	[tciDivision].[CreatedByUserKey],
	CreatedByUser.UserId AS CreatedByUserId,
	[tciDivision].[CreatedOnDate],
	[tciDivision].[DivisionId],
	[tciDivision].[DivisionValue],
	[tciDivision].[LastChanged],
	[tciDivision].[ModifiedByUserKey],
	ModifiedByUser.UserId AS ModifiedByUserId,
	[tciDivision].[ModifiedOnDate],
	[tciDivision].[Name]
FROM
	[dbo].[tciDivision]
LEFT JOIN
	[dbo].[tseUser] CreatedByUser
ON
	[dbo].[tciDivision].[CreatedByUserKey] = CreatedByUser.UserKey
LEFT JOIN
	[dbo].[tseUser] ModifiedByUser
ON
	[dbo].[tciDivision].[ModifiedByUserKey] = ModifiedByUser.UserKey
ORDER BY
	[tciDivision].[DivisionId]
--endregion

GO