--region [dbo].[spseNavigationUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spseNavigationUpdate]
-- Date Generated: Wednesday, June 27, 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spseNavigationUpdate]
		@NavigationKey int,
		@HasChildren bit = 0,
		@IsPrivilegeRequired bit,
		@ModifiedByUserKey int,
		@Name nvarchar(200),
		@NavigationId nvarchar(50),
		@NavigationType int,
		@ParentNavigationKey int,
		@Sequence int,
		@SpriteCssClass nvarchar(50),
		@Url nvarchar(200),
		@LastChanged timestamp,
		@NewLastChanged timestamp OUTPUT
AS

SET NOCOUNT ON

UPDATE [dbo].[tseNavigation] SET
		[HasChildren] = @HasChildren,
		[IsPrivilegeRequired] = @IsPrivilegeRequired,
		[ModifiedByUserKey] = @ModifiedByUserKey,
		ModifiedOnDate = getdate(),
		[Name] = @Name,
		[NavigationId] = @NavigationId,
		[NavigationType] = @NavigationType,
		[ParentNavigationKey] = @ParentNavigationKey,
		[Sequence] = @Sequence,
		[SpriteCssClass] = @SpriteCssClass,
		[Url] = @Url
WHERE
	[tseNavigation].[NavigationKey] = @NavigationKey
AND	
	[tseNavigation].[LastChanged] = @LastChanged

IF	@@ROWCOUNT = 0	
	BEGIN
		RAISERROR('Row has been edited by another user.  Your changes will be lost.',16,1)
	END
	
SELECT 
	@NewLastChanged = LastChanged
FROM 
	[dbo].[tseNavigation]
WHERE 	
	[tseNavigation].[NavigationKey] = @NavigationKey

--endregion

GO	