--region [dbo].[spseNavigationDelete]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spseNavigationDelete]
-- Date Generated: Wednesday, June 27, 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spseNavigationDelete]
	@NavigationKey int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[tseNavigation]
WHERE
	[tseNavigation].[NavigationKey] = @NavigationKey

--endregion

GO