--region [dbo].[spsoSalesOrderTypeSelect]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spsoSalesOrderTypeSelect]
-- Date Generated: Friday, March 27, 2020
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spsoSalesOrderTypeSelect]
	@SalesOrderTypeKey int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT
	[tsoSalesOrderType].[SalesOrderTypeKey],
	[tsoSalesOrderType].[CreatedByUserKey],
	CreatedByUser.UserId AS CreatedByUserId,
	[tsoSalesOrderType].[CreatedOnDate],
	[tsoSalesOrderType].[LastChanged],
	[tsoSalesOrderType].[ModifiedByUserKey],
	ModifiedByUser.UserId AS ModifiedByUserId,
	[tsoSalesOrderType].[ModifiedOnDate],
	[tsoSalesOrderType].[Name],
	[tsoSalesOrderType].[SalesOrderTypeId],
	[tsoSalesOrderType].[SalesOrderTypeValue]
FROM
	[dbo].[tsoSalesOrderType]
LEFT JOIN
	[dbo].[tseUser] CreatedByUser
ON
	[dbo].[tsoSalesOrderType].[CreatedByUserKey] = CreatedByUser.UserKey
LEFT JOIN
	[dbo].[tseUser] ModifiedByUser
ON
	[dbo].[tsoSalesOrderType].[ModifiedByUserKey] = ModifiedByUser.UserKey
WHERE
	[tsoSalesOrderType].[SalesOrderTypeKey] = @SalesOrderTypeKey

--endregion

GO