--region [dbo].[spsoSalesOrderTypeDelete]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spsoSalesOrderTypeDelete]
-- Date Generated: Friday, March 27, 2020
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spsoSalesOrderTypeDelete]
	@SalesOrderTypeKey int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[tsoSalesOrderType]
WHERE
	[tsoSalesOrderType].[SalesOrderTypeKey] = @SalesOrderTypeKey

--endregion

GO