--region [dbo].[spsoSalesOrderStatusInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spsoSalesOrderStatusInsert]
-- Date Generated: Friday, March 27, 2020
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spsoSalesOrderStatusInsert]
		@CreatedByUserKey int,
		@Name nvarchar(200),
		@SalesOrderStatusId nvarchar(50),
		@SalesOrderStatusValue smallint,
		@NewSalesOrderStatusKey int output,
		@NewLastChanged timestamp output
AS

SET NOCOUNT ON

INSERT INTO [dbo].[tsoSalesOrderStatus] (
	[CreatedByUserKey],
	[CreatedOnDate],
	[Name],
	[SalesOrderStatusId],
	[SalesOrderStatusValue]
) VALUES (
	@CreatedByUserKey,
	getdate(),
	@Name,
	@SalesOrderStatusId,
	@SalesOrderStatusValue
)

SET @NewSalesOrderStatusKey = SCOPE_IDENTITY()

SELECT @NewLastChanged = LastChanged
FROM [dbo].[tsoSalesOrderStatus]
WHERE SalesOrderStatusKey = @NewSalesOrderStatusKey

--endregion

GO