--region [dbo].[spsoSalesOrderStatusDelete]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spsoSalesOrderStatusDelete]
-- Date Generated: Friday, March 27, 2020
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spsoSalesOrderStatusDelete]
	@SalesOrderStatusKey int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[tsoSalesOrderStatus]
WHERE
	[tsoSalesOrderStatus].[SalesOrderStatusKey] = @SalesOrderStatusKey

--endregion

GO