--region [dbo].[spsoSalesOrderStatusSelect]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spsoSalesOrderStatusSelect]
-- Date Generated: Friday, March 27, 2020
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spsoSalesOrderStatusSelect]
	@SalesOrderStatusKey int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT
	[tsoSalesOrderStatus].[SalesOrderStatusKey],
	[tsoSalesOrderStatus].[CreatedByUserKey],
	CreatedByUser.UserId AS CreatedByUserId,
	[tsoSalesOrderStatus].[CreatedOnDate],
	[tsoSalesOrderStatus].[LastChanged],
	[tsoSalesOrderStatus].[ModifiedByUserKey],
	ModifiedByUser.UserId AS ModifiedByUserId,
	[tsoSalesOrderStatus].[ModifiedOnDate],
	[tsoSalesOrderStatus].[Name],
	[tsoSalesOrderStatus].[SalesOrderStatusId],
	[tsoSalesOrderStatus].[SalesOrderStatusValue]
FROM
	[dbo].[tsoSalesOrderStatus]
LEFT JOIN
	[dbo].[tseUser] CreatedByUser
ON
	[dbo].[tsoSalesOrderStatus].[CreatedByUserKey] = CreatedByUser.UserKey
LEFT JOIN
	[dbo].[tseUser] ModifiedByUser
ON
	[dbo].[tsoSalesOrderStatus].[ModifiedByUserKey] = ModifiedByUser.UserKey
WHERE
	[tsoSalesOrderStatus].[SalesOrderStatusKey] = @SalesOrderStatusKey

--endregion

GO