--region [dbo].[spsoSalesOrderStatusUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spsoSalesOrderStatusUpdate]
-- Date Generated: Friday, March 27, 2020
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spsoSalesOrderStatusUpdate]
		@SalesOrderStatusKey int,
		@ModifiedByUserKey int,
		@Name nvarchar(200),
		@SalesOrderStatusId nvarchar(50),
		@SalesOrderStatusValue smallint,
		@LastChanged timestamp,
		@NewLastChanged timestamp OUTPUT
AS

SET NOCOUNT ON

UPDATE [dbo].[tsoSalesOrderStatus] SET
		[ModifiedByUserKey] = @ModifiedByUserKey,
		ModifiedOnDate = getdate(),
		[Name] = @Name,
		[SalesOrderStatusId] = @SalesOrderStatusId,
		[SalesOrderStatusValue] = @SalesOrderStatusValue
WHERE
	[tsoSalesOrderStatus].[SalesOrderStatusKey] = @SalesOrderStatusKey
AND	
	[tsoSalesOrderStatus].[LastChanged] = @LastChanged

IF	@@ROWCOUNT = 0	
	BEGIN
		RAISERROR('Row has been edited by another user.  Your changes will be lost.',16,1)
	END
	
SELECT 
	@NewLastChanged = LastChanged
FROM 
	[dbo].[tsoSalesOrderStatus]
WHERE 	
	[tsoSalesOrderStatus].[SalesOrderStatusKey] = @SalesOrderStatusKey

--endregion

GO	