--region [dbo].[spsoSalesOrderTypeInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Text Templates
-- Template:       CRUDTenantStoredProcedures.tt
-- Procedure Name: [dbo].[spsoSalesOrderTypeInsert]
-- Date Generated: Friday, March 27, 2020
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spsoSalesOrderTypeInsert]
		@CreatedByUserKey int,
		@Name nvarchar(200),
		@SalesOrderTypeId nvarchar(50),
		@SalesOrderTypeValue smallint,
		@NewSalesOrderTypeKey int output,
		@NewLastChanged timestamp output
AS

SET NOCOUNT ON

INSERT INTO [dbo].[tsoSalesOrderType] (
	[CreatedByUserKey],
	[CreatedOnDate],
	[Name],
	[SalesOrderTypeId],
	[SalesOrderTypeValue]
) VALUES (
	@CreatedByUserKey,
	getdate(),
	@Name,
	@SalesOrderTypeId,
	@SalesOrderTypeValue
)

SET @NewSalesOrderTypeKey = SCOPE_IDENTITY()

SELECT @NewLastChanged = LastChanged
FROM [dbo].[tsoSalesOrderType]
WHERE SalesOrderTypeKey = @NewSalesOrderTypeKey

--endregion

GO